name: Build spine-libgdx

on:
  push:
    paths:
      - 'spine-libgdx/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build spine-libgdx
      working-directory: spine-libgdx/spine-libgdx
      env:
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: mvn -s ../../.github/workflows/settings.xml clean deploy
